services:

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - '6379:6379'

  backend:
    build: .
    restart: on-failure
    ports:
      - '4000:4000'
    env_file:
      - .env
    environment:
      DATABASE_HOST: db
    depends_on:
      - db
      - redis

volumes:
  db_data:
